server:
  port: 8080

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/community
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MariaDB106Dialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    database: mysql

logging.level:
  org.hibernate.sql: debug